from aiogram.enums import ContentType
from aiogram_dialog import Dialog, Window
from aiogram_dialog.widgets.media import StaticMedia
from aiogram_dialog.widgets.text import Format
from aiogram_dialog.widgets.kbd import Group, Calendar

from bot.dialogs.admin.main.getters import *
from bot.dialogs.admin.main.handlers import *
from bot.dialogs.user.main.handlers import back_general, button_done
from bot.states.state_user import StateAdmin

admin_menu_dialog = Dialog(
    Window(
        Format('{main_text}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        Group(
            Button(
                text=Format('{milling}'),
                id='milling',
                on_click=button_milling
            ),
            Button(
                text=Format('{statistic}'),
                id='statistic',
                on_click=button_statistic
            ),
            Button(
                text=Format('{user_control}'),
                id='user_control',
                on_click=button_user_control_input
            ),
            Button(
            text=Format('{back}'),
            id='back',
            on_click=back_general
            )
        ),
        getter=get_admin_menu,
        state=StateAdmin.admin_menu,
    ),
    Window(
        Format('{milling_group_text}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        Button(
            text=Format('{all_users}'),
            id='all_users',
            on_click=button_milling_group
        ),
        Button(
            text=Format('{subscribe_users}'),
            id='subscribe_users',
            on_click=button_milling_group
        ),
        Button(
            text=Format('{not_subscribe_users}'),
            id='not_subscribe_users',
            on_click=button_milling_group
        ),
        Button(
            text=Format('{back}'),
            id='back',
            on_click=back_admin_menu
        ),
        getter=get_milling_group_admin,
        state=StateAdmin.milling_menu
    ),
    Window(
        Format('{milling_text}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        MessageInput(
            func=milling_input_handler,
            content_types=ContentType.ANY
        ),
        Button(
            text=Format('{back}'),
            id='back',
            on_click=button_milling
        ),
        getter=get_milling_active_admin,
        state=StateAdmin.milling_active
    ),
    Window(
        Format('{statistic_text}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        Group(
            Button(
                text=Format('{payments}'),
                id='payments',
                on_click=show_payments
            ),
            Button(
                text=Format('{all_users}'),
                id='all_users',
                on_click=show_users
            ),
            Button(
                text=Format('{active_users}'),
                id='active_users',
                on_click=show_users
            ),
            Button(
                text=Format('{back}'),
                id='back',
                on_click=back_admin_menu
            ),
        ),
        getter=get_statistic_admin,
        state=StateAdmin.statistics_menu
    ),
    Window(
        Format('{user_control_text}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        MessageInput(
            func=input_id_user_handler,
            content_types=ContentType.TEXT
        ),
        Button(
            text=Format('{back}'),
            id='back',
            on_click=back_admin_menu
        ),
        getter=get_user_control_input,
        state=StateAdmin.user_control_input
    ),
    Window(
        Format('{user_control_account_text}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        Button(
            text=Format('{ban_unban_user}'),
            id='ban_unban_user',
            on_click=ban_unban_user_handler
        ),
        Button(
            text=Format('{message_user}'),
            id='message_user',
            on_click=message_user_handler
        ),
        Button(
            text=Format('{add_time}'),
            id='add_time',
            on_click=add_time_user_handler
        ),
        Button(
            text=Format('{payments_user}'),
            id='payments_user',
            on_click=show_payments
        ),
        Button(
            text=Format('{ban_user}'),
            id='ban_user',
            on_click=ban_user_handler
        ),
        Button(
            text=Format('{back}'),
            id='back',
            on_click=back_admin_menu
        ),
        getter=get_user_control_account,
        state=StateAdmin.user_control_menu
    ),
    Window(
        Format('{user_control_message_user}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        MessageInput(
            func=input_message_user_handler,
            content_types=ContentType.ANY
        ),
        Button(
            text=Format('{back}'),
            id='back',
            on_click=back_user_control_handler
        ),
        getter=get_user_control_message_user,
        state=StateAdmin.user_control_message
    ),
Window(
        Format('{user_control_add_time}'),
        StaticMedia(
            path='bot/img/logo.png',
            type=ContentType.PHOTO
        ),
        Calendar(
            id='calendar',
            on_click=on_date_selected
        ),
        Button(
            text=Format('{back}'),
            id='back',
            on_click=back_user_control_handler
        ),
        getter=get_user_control_add_time,
        state=StateAdmin.user_control_add_time
    ),
)
